# Generated by Django 5.2.5 on 2025-08-20 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'variacao', 'verbose_name_plural': 'variacoes'},
        ),
    ]
